const API='/.netlify/git/github';
const BRANCH='main';
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const state={user:null,catalog:null,site:null,shas:{},dirty:new Set(),changes:0,uploads:new Map(),started:false};

function toast(message,error=false){const box=$('[data-toast]');box.textContent=message;box.classList.toggle('error',error);box.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>box.hidden=true,4500)}
function encodeText(value){const bytes=new TextEncoder().encode(value);let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary)}
function decodeText(value){const clean=value.replace(/\s/g,'');const bytes=Uint8Array.from(atob(clean),char=>char.charCodeAt(0));return new TextDecoder().decode(bytes)}
async function token(){return state.user.jwt()}
async function api(path,options={}){const response=await fetch(`${API}${path}`,{...options,headers:{Authorization:`Bearer ${await token()}`,'Content-Type':'application/json',...(options.headers||{})}});if(!response.ok){let detail='';try{detail=(await response.json()).message||''}catch{}throw new Error(detail||`Eroare ${response.status}`)}return response.json()}
async function loadFile(path){const result=await api(`/contents/${path}?ref=${BRANCH}`);return{data:JSON.parse(decodeText(result.content)),sha:result.sha}}
async function saveFile(path,data,sha,message){return api(`/contents/${path}`,{method:'PUT',body:JSON.stringify({message,content:encodeText(JSON.stringify(data,null,2)+'\n'),branch:BRANCH,sha})})}

function markDirty(type){state.dirty.add(type);state.changes++;const bar=$('[data-publish-bar]');bar.hidden=false;$('[data-change-count]').textContent=state.changes===1?'Ai o modificare nepublicată':`Ai ${state.changes} modificări nepublicate`}
function categoryName(slug){return state.catalog.categories.find(category=>category.slug===slug)?.name||slug}
function safeId(value){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`produs-${Date.now()}`}
function pendingPath(key){return `pending://${key}`}
function isPending(path){return String(path||'').startsWith('pending://')}
function imageSource(path){if(isPending(path)){const item=state.uploads.get(path.slice(10));return item?.url||''}return `../${String(path||'').replace(/^\//,'')}`}
function registerFile(file){const key=crypto.randomUUID();state.uploads.set(key,{file,url:URL.createObjectURL(file),uploadedPath:null});return pendingPath(key)}
function formattedDate(value){if(!value)return'';return new Intl.DateTimeFormat('ro-RO',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${value}T12:00:00`))}

function populateCategories(){const options=state.catalog.categories.map(category=>`<option value="${category.slug}">${category.name}</option>`).join('');$('[data-category-filter]').insertAdjacentHTML('beforeend',options);$('[data-product-form] [name="category"]').innerHTML=options}
function renderProducts(){const search=$('[data-product-search]').value.trim().toLowerCase(),category=$('[data-category-filter]').value;const entries=state.catalog.products.map((product,index)=>({product,index})).filter(({product})=>(!category||product.category===category)&&(!search||product.name.toLowerCase().includes(search)));$('[data-product-count]').textContent=`${entries.length} ${entries.length===1?'produs':'produse'}`;const host=$('[data-product-list]');if(!entries.length){host.innerHTML='<div class="empty"><h2>Nu am găsit produse</h2><p>Schimbă filtrul sau adaugă o mobilă nouă.</p></div>';return}host.innerHTML=entries.map(({product,index})=>{
    const images=[product.image,...(product.gallery||[])].filter(Boolean);
    return `<article class="product-admin-card ${product.available===false?'inactive':''}"><img class="product-cover" src="${imageSource(product.image)}" alt=""><div class="product-summary"><div><span class="category-pill">${categoryName(product.category)}</span> <span class="visibility-pill ${product.available===false?'hidden-product':''}">${product.available===false?'Ascuns':'Vizibil'}</span></div><h2>${escapeHtml(product.name)}</h2><p class="product-description">${escapeHtml(product.description)}</p><div class="specs"><span><strong>Dimensiuni:</strong> ${escapeHtml(product.dimensions)}</span><span><strong>Materiale:</strong> ${escapeHtml(product.materials)}</span><span><strong>Poze:</strong> ${images.length}</span></div><div class="mini-gallery">${images.map((image,i)=>`<img src="${imageSource(image)}" alt="Fotografia ${i+1}">`).join('')}</div></div><div class="card-actions"><button class="button secondary" type="button" data-edit-product="${index}">Modifică</button><button class="button ghost" type="button" data-delete-product="${index}">Șterge</button></div></article>`
  }).join('');
}
function escapeHtml(value){return String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]))}

function renderEditGallery(){const host=$('[data-edit-gallery]'),gallery=JSON.parse(host.dataset.gallery||'[]');host.innerHTML=gallery.map((image,index)=>`<div class="editable-photo"><img src="${imageSource(image)}" alt=""><button type="button" data-remove-gallery="${index}" aria-label="Șterge fotografia">×</button></div>`).join('')}
function openProduct(index=null){const form=$('[data-product-form]'),fields=form.elements;form.reset();fields.editingIndex.value=index??'';const product=index===null?null:state.catalog.products[index];$('[data-product-dialog-title]').textContent=product?'Modifică mobila':'Adaugă mobilă';fields.name.value=product?.name||'';fields.category.value=product?.category||state.catalog.categories[0]?.slug||'';fields.shortDescription.value=product?.shortDescription||'';fields.description.value=product?.description||'';fields.dimensions.value=product?.dimensions||'';fields.materials.value=product?.materials||'';fields.available.checked=product?.available!==false;$('[data-current-main-image]').textContent=product?.image?`Imagine actuală: ${product.image.split('/').pop()}`:'Este necesară o fotografie principală.';$('[data-edit-gallery]').dataset.gallery=JSON.stringify(product?.gallery||[]);renderEditGallery();$('[data-product-dialog]').showModal()}
function saveProduct(event){event.preventDefault();const form=event.currentTarget,fields=form.elements;if(!form.reportValidity())return;const index=fields.editingIndex.value===''?null:Number(fields.editingIndex.value),old=index===null?null:state.catalog.products[index];const primaryFile=fields.mainImage.files[0];if(!old&&!primaryFile){toast('Selectează fotografia principală.',true);return}const galleryFiles=[...fields.galleryImages.files];const name=fields.name.value.trim();const usedIds=new Set(state.catalog.products.filter((_,i)=>i!==index).map(item=>item.id));let id=old?.id||safeId(name);if(usedIds.has(id)){let suffix=2;while(usedIds.has(`${id}-${suffix}`))suffix++;id=`${id}-${suffix}`}const gallery=JSON.parse($('[data-edit-gallery]').dataset.gallery||'[]');const product={id,name,category:fields.category.value,image:primaryFile?registerFile(primaryFile):old.image,gallery:[...gallery,...galleryFiles.map(registerFile)],shortDescription:fields.shortDescription.value.trim(),description:fields.description.value.trim(),dimensions:fields.dimensions.value.trim(),materials:fields.materials.value.trim(),available:fields.available.checked};if(index===null)state.catalog.products.unshift(product);else state.catalog.products[index]=product;markDirty('catalog');renderProducts();$('[data-product-dialog]').close();toast('Produs salvat. Apasă „Publică” când ai terminat.')}

async function confirmDelete(){const dialog=$('[data-confirm-dialog]');dialog.showModal();return new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue==='confirm'),{once:true}))}
async function deleteProduct(index){if(!await confirmDelete())return;state.catalog.products.splice(index,1);markDirty('catalog');renderProducts();toast('Produsul este pregătit pentru ștergere.')}

function renderNews(){const host=$('[data-news-list]'),news=state.site.announcements||[];if(!news.length){host.innerHTML='<div class="empty"><h2>Nu există noutăți</h2><p>Adaugă primul mesaj pentru clienți.</p></div>';return}host.innerHTML=news.map((item,index)=>`<article class="news-admin-card">${item.image?`<img src="${imageSource(item.image)}" alt="">`:''}<div class="news-admin-body"><span class="news-date">${formattedDate(item.date)} · ${item.published===false?'Ascunsă':'Vizibilă'}</span><h2>${escapeHtml(item.title)}</h2><p>${escapeHtml(item.message)}</p><div class="card-actions"><button class="button secondary" type="button" data-edit-news="${index}">Modifică</button><button class="button ghost" type="button" data-delete-news="${index}">Șterge</button></div></div></article>`).join('')}
function openNews(index=null){const form=$('[data-news-form]'),fields=form.elements;form.reset();fields.editingIndex.value=index??'';const item=index===null?null:state.site.announcements[index];$('[data-news-dialog-title]').textContent=item?'Modifică noutatea':'Adaugă noutate';fields.title.value=item?.title||'';fields.message.value=item?.message||'';fields.date.value=item?.date||new Date().toISOString().slice(0,10);fields.buttonText.value=item?.buttonText||'';fields.buttonLink.value=item?.buttonLink||'';fields.published.checked=item?.published!==false;$('[data-current-news-image]').textContent=item?.image?`Imagine actuală: ${item.image.split('/').pop()}`:'Fotografia este opțională.';$('[data-news-dialog]').showModal()}
function saveNews(event){event.preventDefault();const form=event.currentTarget,fields=form.elements;if(!form.reportValidity())return;const index=fields.editingIndex.value===''?null:Number(fields.editingIndex.value),old=index===null?null:state.site.announcements[index],file=fields.imageFile.files[0];const item={title:fields.title.value.trim(),message:fields.message.value.trim(),date:fields.date.value,image:file?registerFile(file):(old?.image||''),buttonText:fields.buttonText.value.trim(),buttonLink:fields.buttonLink.value.trim(),published:fields.published.checked};if(index===null)state.site.announcements.unshift(item);else state.site.announcements[index]=item;markDirty('site');renderNews();$('[data-news-dialog]').close();toast('Noutatea a fost salvată în așteptare.')}
async function deleteNews(index){if(!await confirmDelete())return;state.site.announcements.splice(index,1);markDirty('site');renderNews();toast('Noutatea este pregătită pentru ștergere.')}

function getNested(object,path){return path.split('.').reduce((value,key)=>value?.[key],object)}
function fillSettings(){const form=$('[data-settings-form]');$$('[data-settings-form] [name]').forEach(field=>{if(field.type!=='file')field.value=getNested(state.site,field.name)??''});$('[data-hero-image-name]').textContent=`Imagine actuală: ${state.site.hero.image.split('/').pop()}`}
function saveSettings(event){event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;for(const field of form.elements){if(!field.name||field.type==='file'||field.type==='submit')continue;const [group,key]=field.name.split('.');if(state.site[group]&&key)state.site[group][key]=field.value.trim()}const file=form.elements['hero.imageFile'].files[0];if(file)state.site.hero.image=registerFile(file);const phoneLink=value=>{const digits=value.replace(/\D/g,'');return digits.startsWith('0')?`40${digits.slice(1)}`:digits};state.site.contact.primaryPhoneLink=phoneLink(state.site.contact.primaryPhoneDisplay);state.site.contact.secondaryPhoneLink=phoneLink(state.site.contact.secondaryPhoneDisplay);markDirty('site');fillSettings();toast('Pagina principală este salvată în așteptare.')}

function fileBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)})}
function uploadName(file){const dot=file.name.lastIndexOf('.'),raw=dot>0?file.name.slice(0,dot):file.name,ext=dot>0?file.name.slice(dot).toLowerCase():'.jpg';const clean=safeId(raw).slice(0,55);return `${Date.now()}-${Math.random().toString(36).slice(2,7)}-${clean}${ext}`}
async function uploadPending(){for(const [key,item] of state.uploads){if(item.uploadedPath)continue;const path=`assets/uploads/${uploadName(item.file)}`;await api(`/contents/${path}`,{method:'PUT',body:JSON.stringify({message:`Adaugă fotografia ${item.file.name}`,content:await fileBase64(item.file),branch:BRANCH})});item.uploadedPath=`/${path}`}}
function replacePending(path){if(!isPending(path))return path;return state.uploads.get(path.slice(10))?.uploadedPath||path}
function applyUploadedPaths(){state.catalog.products.forEach(product=>{product.image=replacePending(product.image);product.gallery=(product.gallery||[]).map(replacePending)});state.site.hero.image=replacePending(state.site.hero.image);state.site.announcements.forEach(item=>item.image=replacePending(item.image))}
async function publish(){const button=$('[data-publish]');button.disabled=true;button.textContent='Se publică…';try{await uploadPending();applyUploadedPaths();if(state.dirty.has('catalog')){const result=await saveFile('data/catalog.json',state.catalog,state.shas.catalog,'Actualizează mobilierul din panoul simplu');state.shas.catalog=result.content?.sha||result.sha||state.shas.catalog}if(state.dirty.has('site')){const result=await saveFile('data/site.json',state.site,state.shas.site,'Actualizează pagina și noutățile');state.shas.site=result.content?.sha||result.sha||state.shas.site}state.dirty.clear();state.changes=0;state.uploads.clear();$('[data-publish-bar]').hidden=true;renderProducts();renderNews();fillSettings();toast('Publicat! Site-ul se actualizează automat în câteva momente.')}catch(error){console.error(error);toast(`Nu am putut publica: ${error.message}`,true)}finally{button.disabled=false;button.textContent='Publică modificările pe site'}}

function bindEvents(){$$('[data-tab]').forEach(button=>button.addEventListener('click',()=>{$$('[data-tab]').forEach(item=>item.classList.toggle('active',item===button));$$('[data-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.panel===button.dataset.tab))}));$('[data-product-search]').addEventListener('input',renderProducts);$('[data-category-filter]').addEventListener('change',renderProducts);$('[data-add-product]').addEventListener('click',()=>openProduct());$('[data-product-form]').addEventListener('submit',saveProduct);$$('[data-close-product]').forEach(button=>button.addEventListener('click',()=>$('[data-product-dialog]').close()));$('[data-edit-gallery]').addEventListener('click',event=>{const remove=event.target.closest('[data-remove-gallery]');if(!remove)return;const host=$('[data-edit-gallery]'),gallery=JSON.parse(host.dataset.gallery||'[]');gallery.splice(Number(remove.dataset.removeGallery),1);host.dataset.gallery=JSON.stringify(gallery);renderEditGallery()});$('[data-product-list]').addEventListener('click',event=>{const edit=event.target.closest('[data-edit-product]'),remove=event.target.closest('[data-delete-product]');if(edit)openProduct(Number(edit.dataset.editProduct));if(remove)deleteProduct(Number(remove.dataset.deleteProduct))});$('[data-add-news]').addEventListener('click',()=>openNews());$('[data-news-form]').addEventListener('submit',saveNews);$$('[data-close-news]').forEach(button=>button.addEventListener('click',()=>$('[data-news-dialog]').close()));$('[data-news-list]').addEventListener('click',event=>{const edit=event.target.closest('[data-edit-news]'),remove=event.target.closest('[data-delete-news]');if(edit)openNews(Number(edit.dataset.editNews));if(remove)deleteNews(Number(remove.dataset.deleteNews))});$('[data-settings-form]').addEventListener('submit',saveSettings);$('[data-publish]').addEventListener('click',publish);$('[data-logout]').addEventListener('click',()=>netlifyIdentity.logout())}

async function start(user){if(state.started)return;state.started=true;state.user=user;$('[data-login-screen]').hidden=true;$('[data-app]').hidden=false;$('[data-user-email]').textContent=user.email||'';try{const [catalog,site]=await Promise.all([loadFile('data/catalog.json'),loadFile('data/site.json')]);state.catalog=catalog.data;state.site=site.data;state.site.announcements||=[];state.shas={catalog:catalog.sha,site:site.sha};populateCategories();renderProducts();renderNews();fillSettings();bindEvents()}catch(error){console.error(error);toast(`Nu am putut încărca datele: ${error.message}`,true)}}
function showLogin(){state.started=false;state.user=null;$('[data-app]').hidden=true;$('[data-login-screen]').hidden=false}

$('[data-login]').addEventListener('click',()=>netlifyIdentity.open('login'));
netlifyIdentity.on('init',user=>user?start(user):showLogin());
netlifyIdentity.on('login',user=>{netlifyIdentity.close();start(user)});
netlifyIdentity.on('logout',showLogin);
