const API='/.netlify/git/github';
const BRANCH='main';
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const state={user:null,catalog:null,publishedCatalog:null,site:null,shas:{},dirty:new Set(),changes:0,uploads:new Map(),started:false};

function toast(message,error=false){const box=$('[data-toast]');box.textContent=message;box.classList.toggle('error',error);box.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>box.hidden=true,4500)}
function encodeText(value){const bytes=new TextEncoder().encode(value);let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary)}
function decodeText(value){const clean=value.replace(/\s/g,'');const bytes=Uint8Array.from(atob(clean),char=>char.charCodeAt(0));return new TextDecoder().decode(bytes)}
async function token(){return state.user.jwt()}
async function api(path,options={}){const response=await fetch(`${API}${path}`,{...options,headers:{Authorization:`Bearer ${await token()}`,'Content-Type':'application/json',...(options.headers||{})}});if(!response.ok){let detail='';try{detail=(await response.json()).message||''}catch{}const error=new Error(detail||`Eroare ${response.status}`);error.status=response.status;throw error}return response.json()}
async function loadFile(path){const result=await api(`/contents/${path}?ref=${BRANCH}`);return{data:JSON.parse(decodeText(result.content)),sha:result.sha}}
async function saveFile(path,data,sha,message){return api(`/contents/${path}`,{method:'PUT',body:JSON.stringify({message,content:encodeText(JSON.stringify(data,null,2)+'\n'),branch:BRANCH,sha})})}
async function loadTextFile(path){try{const result=await api(`/contents/${path}?ref=${BRANCH}`);return{text:decodeText(result.content),sha:result.sha}}catch(error){if(error.status===404)return null;throw error}}
async function saveTextFile(path,text,message){const current=await loadTextFile(path);if(current?.text===text)return current;const body={message,content:encodeText(text),branch:BRANCH};if(current?.sha)body.sha=current.sha;return api(`/contents/${path}`,{method:'PUT',body:JSON.stringify(body)})}
async function deleteTextFile(path,message){const current=await loadTextFile(path);if(!current)return;return api(`/contents/${path}`,{method:'DELETE',body:JSON.stringify({message,sha:current.sha,branch:BRANCH})})}
function cloneData(value){return typeof structuredClone==='function'?structuredClone(value):JSON.parse(JSON.stringify(value))}

function markDirty(type){state.dirty.add(type);state.changes++;const bar=$('[data-publish-bar]');bar.hidden=false;$('[data-change-count]').textContent=state.changes===1?'Ai o modificare nepublicată':`Ai ${state.changes} modificări nepublicate`}
function categoryName(slug){return state.catalog.categories.find(category=>category.slug===slug)?.name||slug}
function safeId(value){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`produs-${Date.now()}`}
function pendingPath(key){return `pending://${key}`}
function isPending(path){return String(path||'').startsWith('pending://')}
function imageSource(path){if(isPending(path)){const item=state.uploads.get(path.slice(10));return item?.url||''}return `../${String(path||'').replace(/^\//,'')}`}
function registerFile(file){const key=crypto.randomUUID();state.uploads.set(key,{file,url:URL.createObjectURL(file),uploadedPath:null});return pendingPath(key)}
function formattedDate(value){if(!value)return'';return new Intl.DateTimeFormat('ro-RO',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${value}T12:00:00`))}

function populateCategories(){const options=state.catalog.categories.map(category=>`<option value="${category.slug}">${category.name}</option>`).join('');$('[data-category-filter]').insertAdjacentHTML('beforeend',options);$('[data-product-form] [name="category"]').innerHTML=options}
function renderProducts(){const search=$('[data-product-search]').value.trim().toLowerCase(),category=$('[data-category-filter]').value;const entries=state.catalog.products.map((product,index)=>({product,index})).filter(({product})=>(!category||product.category===category)&&(!search||product.name.toLowerCase().includes(search)));$('[data-product-count]').textContent=`${entries.length} ${entries.length===1?'produs':'produse'}`;const host=$('[data-product-list]');if(!entries.length){host.innerHTML='<div class="empty"><h2>Nu am găsit produse</h2><p>Schimbă filtrul sau adaugă o mobilă nouă.</p></div>';return}host.innerHTML=entries.map(({product,index})=>{
    const images=[product.image,...(product.gallery||[])].filter(Boolean);
    return `<article class="product-admin-card ${product.available===false?'inactive':''}"><img class="product-cover" src="${imageSource(product.image)}" alt=""><div class="product-summary"><div><span class="category-pill">${categoryName(product.category)}</span> <span class="visibility-pill ${product.available===false?'hidden-product':''}">${product.available===false?'Ascuns':'Vizibil'}</span></div><h2>${escapeHtml(product.name)}</h2><p class="product-description">${escapeHtml(product.description)}</p><div class="specs"><span><strong>Dimensiuni:</strong> ${escapeHtml(product.dimensions)}</span><span><strong>Materiale:</strong> ${escapeHtml(product.materials)}</span><span><strong>Poze:</strong> ${images.length}</span></div><div class="mini-gallery">${images.map((image,i)=>`<img src="${imageSource(image)}" alt="Fotografia ${i+1}">`).join('')}</div></div><div class="card-actions"><button class="button secondary" type="button" data-edit-product="${index}">Modifică</button><button class="button ghost" type="button" data-delete-product="${index}">Șterge</button></div></article>`
  }).join('');
}
function escapeHtml(value){return String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]))}

function renderEditGallery(){const host=$('[data-edit-gallery]'),gallery=JSON.parse(host.dataset.gallery||'[]');host.innerHTML=gallery.map((image,index)=>`<div class="editable-photo"><img src="${imageSource(image)}" alt=""><button type="button" data-remove-gallery="${index}" aria-label="Șterge fotografia">×</button></div>`).join('')}
function openProduct(index=null){const form=$('[data-product-form]'),fields=form.elements;form.reset();fields.editingIndex.value=index??'';const product=index===null?null:state.catalog.products[index];$('[data-product-dialog-title]').textContent=product?'Modifică mobila':'Adaugă mobilă';fields.name.value=product?.name||'';fields.category.value=product?.category||state.catalog.categories[0]?.slug||'';fields.shortDescription.value=product?.shortDescription||'';fields.description.value=product?.description||'';fields.dimensions.value=product?.dimensions||'';fields.materials.value=product?.materials||'';fields.available.checked=product?.available!==false;$('[data-current-main-image]').textContent=product?.image?`Imagine actuală: ${product.image.split('/').pop()}`:'Este necesară o fotografie principală.';$('[data-edit-gallery]').dataset.gallery=JSON.stringify(product?.gallery||[]);renderEditGallery();$('[data-product-dialog]').showModal()}
function saveProduct(event){event.preventDefault();const form=event.currentTarget,fields=form.elements;if(!form.reportValidity())return;const index=fields.editingIndex.value===''?null:Number(fields.editingIndex.value),old=index===null?null:state.catalog.products[index];const primaryFile=fields.mainImage.files[0];if(!old&&!primaryFile){toast('Selectează fotografia principală.',true);return}const galleryFiles=[...fields.galleryImages.files];const name=fields.name.value.trim();const usedIds=new Set(state.catalog.products.filter((_,i)=>i!==index).map(item=>item.id));let id=old?.id||safeId(name);if(usedIds.has(id)){let suffix=2;while(usedIds.has(`${id}-${suffix}`))suffix++;id=`${id}-${suffix}`}const gallery=JSON.parse($('[data-edit-gallery]').dataset.gallery||'[]');const product={id,name,category:fields.category.value,image:primaryFile?registerFile(primaryFile):old.image,gallery:[...gallery,...galleryFiles.map(registerFile)],shortDescription:fields.shortDescription.value.trim(),description:fields.description.value.trim(),dimensions:fields.dimensions.value.trim(),materials:fields.materials.value.trim(),available:fields.available.checked};if(index===null)state.catalog.products.unshift(product);else state.catalog.products[index]=product;markDirty('catalog');renderProducts();$('[data-product-dialog]').close();toast('Produs salvat. Apasă „Publică” când ai terminat.')}

async function confirmDelete(){const dialog=$('[data-confirm-dialog]');dialog.showModal();return new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue==='confirm'),{once:true}))}
async function deleteProduct(index){if(!await confirmDelete())return;state.catalog.products.splice(index,1);markDirty('catalog');renderProducts();toast('Produsul este pregătit pentru ștergere.')}

function renderNews(){const host=$('[data-news-list]'),news=state.site.announcements||[];if(!news.length){host.innerHTML='<div class="empty"><h2>Nu există noutăți</h2><p>Adaugă primul mesaj pentru clienți.</p></div>';return}host.innerHTML=news.map((item,index)=>`<article class="news-admin-card">${item.image?`<img src="${imageSource(item.image)}" alt="">`:''}<div class="news-admin-body"><span class="news-date">${formattedDate(item.date)} · ${item.published===false?'Ascunsă':'Vizibilă'}</span><h2>${escapeHtml(item.title)}</h2><p>${escapeHtml(item.message)}</p><div class="card-actions"><button class="button secondary" type="button" data-edit-news="${index}">Modifică</button><button class="button ghost" type="button" data-delete-news="${index}">Șterge</button></div></div></article>`).join('')}
function openNews(index=null){const form=$('[data-news-form]'),fields=form.elements;form.reset();fields.editingIndex.value=index??'';const item=index===null?null:state.site.announcements[index];$('[data-news-dialog-title]').textContent=item?'Modifică noutatea':'Adaugă noutate';fields.title.value=item?.title||'';fields.message.value=item?.message||'';fields.date.value=item?.date||new Date().toISOString().slice(0,10);fields.buttonText.value=item?.buttonText||'';fields.buttonLink.value=item?.buttonLink||'';fields.published.checked=item?.published!==false;$('[data-current-news-image]').textContent=item?.image?`Imagine actuală: ${item.image.split('/').pop()}`:'Fotografia este opțională.';$('[data-news-dialog]').showModal()}
function saveNews(event){event.preventDefault();const form=event.currentTarget,fields=form.elements;if(!form.reportValidity())return;const index=fields.editingIndex.value===''?null:Number(fields.editingIndex.value),old=index===null?null:state.site.announcements[index],file=fields.imageFile.files[0];const item={title:fields.title.value.trim(),message:fields.message.value.trim(),date:fields.date.value,image:file?registerFile(file):(old?.image||''),buttonText:fields.buttonText.value.trim(),buttonLink:fields.buttonLink.value.trim(),published:fields.published.checked};if(index===null)state.site.announcements.unshift(item);else state.site.announcements[index]=item;markDirty('site');renderNews();$('[data-news-dialog]').close();toast('Noutatea a fost salvată în așteptare.')}
async function deleteNews(index){if(!await confirmDelete())return;state.site.announcements.splice(index,1);markDirty('site');renderNews();toast('Noutatea este pregătită pentru ștergere.')}

function renderTestimonials(){const host=$('[data-testimonial-list]'),items=state.site.testimonials||[];if(!items.length){host.innerHTML='<div class="empty"><h2>Nu există încă lucrări publicate</h2><p>Adaugă primul client mulțumit și fotografia montajului.</p></div>';return}host.innerHTML=items.map((item,index)=>`<article class="news-admin-card">${item.image?`<img src="${imageSource(item.image)}" alt="">`:''}<div class="news-admin-body"><span class="news-date">${formattedDate(item.date)} · ${item.published===false?'Ascuns':'Vizibil'}</span><h2>${escapeHtml(item.clientName)}</h2><p><strong>${escapeHtml(item.furniture)}</strong> · ${escapeHtml(item.location)}</p><p>${escapeHtml(item.review)}</p><div class="card-actions"><button class="button secondary" type="button" data-edit-testimonial="${index}">Modifică</button><button class="button ghost" type="button" data-delete-testimonial="${index}">Șterge</button></div></div></article>`).join('')}
function openTestimonial(index=null){const form=$('[data-testimonial-form]'),fields=form.elements;form.reset();fields.editingIndex.value=index??'';const item=index===null?null:state.site.testimonials[index];$('[data-testimonial-dialog-title]').textContent=item?'Modifică lucrarea':'Adaugă client mulțumit';fields.clientName.value=item?.clientName||'';fields.location.value=item?.location||'';fields.furniture.value=item?.furniture||'';fields.review.value=item?.review||'';fields.date.value=item?.date||new Date().toISOString().slice(0,10);fields.consentConfirmed.checked=item?.consentConfirmed===true;fields.published.checked=item?.published!==false;$('[data-current-testimonial-image]').textContent=item?.image?`Imagine actuală: ${item.image.split('/').pop()}`:'Este necesară o fotografie a montajului.';$('[data-testimonial-dialog]').showModal()}
function saveTestimonial(event){event.preventDefault();const form=event.currentTarget,fields=form.elements;if(!form.reportValidity())return;const index=fields.editingIndex.value===''?null:Number(fields.editingIndex.value),old=index===null?null:state.site.testimonials[index],file=fields.imageFile.files[0];if(!old&&!file){toast('Selectează fotografia montajului.',true);return}const item={clientName:fields.clientName.value.trim(),location:fields.location.value.trim(),furniture:fields.furniture.value.trim(),review:fields.review.value.trim(),date:fields.date.value,image:file?registerFile(file):old.image,consentConfirmed:fields.consentConfirmed.checked,published:fields.published.checked};if(index===null)state.site.testimonials.unshift(item);else state.site.testimonials[index]=item;markDirty('site');renderTestimonials();$('[data-testimonial-dialog]').close();toast('Lucrarea a fost salvată în așteptare.')}
async function deleteTestimonial(index){if(!await confirmDelete())return;state.site.testimonials.splice(index,1);markDirty('site');renderTestimonials();toast('Lucrarea este pregătită pentru ștergere.')}

function getNested(object,path){return path.split('.').reduce((value,key)=>value?.[key],object)}
function fillSettings(){const form=$('[data-settings-form]');$$('[data-settings-form] [name]').forEach(field=>{if(field.type!=='file')field.value=getNested(state.site,field.name)??''});$('[data-hero-image-name]').textContent=`Imagine actuală: ${state.site.hero.image.split('/').pop()}`}
function saveSettings(event){event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;for(const field of form.elements){if(!field.name||field.type==='file'||field.type==='submit')continue;const [group,key]=field.name.split('.');if(state.site[group]&&key)state.site[group][key]=field.value.trim()}const file=form.elements['hero.imageFile'].files[0];if(file)state.site.hero.image=registerFile(file);const phoneLink=value=>{const digits=value.replace(/\D/g,'');return digits.startsWith('0')?`40${digits.slice(1)}`:digits};state.site.contact.primaryPhoneLink=phoneLink(state.site.contact.primaryPhoneDisplay);state.site.contact.secondaryPhoneLink=phoneLink(state.site.contact.secondaryPhoneDisplay);markDirty('site');fillSettings();toast('Pagina principală este salvată în așteptare.')}

function fileBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)})}
const MAX_IMAGE_WIDTH=1600;
const TARGET_UPLOAD_BYTES=900*1024;
function canvasJpeg(canvas,quality){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Imaginea nu a putut fi comprimată.')),'image/jpeg',quality))}
function loadImageElement(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),image=new Image();image.onload=()=>resolve({image,release:()=>URL.revokeObjectURL(url)});image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error(`Imaginea ${file.name} nu a putut fi citită.`))};image.src=url})}
async function compressImage(file){
  let source,release=()=>{};
  try{
    if('createImageBitmap' in window){
      try{source=await createImageBitmap(file,{imageOrientation:'from-image'});release=()=>source.close?.()}catch{}
    }
    if(!source){const loaded=await loadImageElement(file);source=loaded.image;release=loaded.release}
    const sourceWidth=source.naturalWidth||source.width,sourceHeight=source.naturalHeight||source.height;
    if(!sourceWidth||!sourceHeight)throw new Error(`Imaginea ${file.name} nu are dimensiuni valide.`);
    let width=Math.min(sourceWidth,MAX_IMAGE_WIDTH),height=Math.round(sourceHeight*(width/sourceWidth)),quality=.8,blob;
    const canvas=document.createElement('canvas'),context=canvas.getContext('2d',{alpha:false});
    if(!context)throw new Error('Browserul nu poate comprima această imagine.');
    for(let attempt=0;attempt<8;attempt++){
      canvas.width=Math.max(1,Math.round(width));canvas.height=Math.max(1,Math.round(height));
      context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(source,0,0,canvas.width,canvas.height);
      blob=await canvasJpeg(canvas,quality);
      if(blob.size<=TARGET_UPLOAD_BYTES)break;
      if(quality>.6)quality=Math.max(.6,quality-.08);
      else{width=Math.round(width*.88);height=Math.round(height*.88)}
    }
    if(!blob)throw new Error(`Imaginea ${file.name} nu a putut fi comprimată.`);
    const raw=file.name.replace(/\.[^.]+$/,'');
    return new File([blob],`${raw||'fotografie'}.jpg`,{type:'image/jpeg',lastModified:file.lastModified||Date.now()});
  }finally{release()}
}
function uploadName(file){const dot=file.name.lastIndexOf('.'),raw=dot>0?file.name.slice(0,dot):file.name,ext=dot>0?file.name.slice(dot).toLowerCase():'.jpg';const clean=safeId(raw).slice(0,55);return `${Date.now()}-${Math.random().toString(36).slice(2,7)}-${clean}${ext}`}
async function uploadPending(){for(const [key,item] of state.uploads){if(item.uploadedPath)continue;const originalName=item.file.name,compressed=await compressImage(item.file),path=`assets/uploads/${uploadName(compressed)}`;await api(`/contents/${path}`,{method:'PUT',body:JSON.stringify({message:`Adaugă fotografia ${originalName}`,content:await fileBase64(compressed),branch:BRANCH})});item.file=compressed;item.uploadedPath=`/${path}`}}
function replacePending(path){if(!isPending(path))return path;return state.uploads.get(path.slice(10))?.uploadedPath||path}
function applyUploadedPaths(){state.catalog.products.forEach(product=>{product.image=replacePending(product.image);product.gallery=(product.gallery||[]).map(replacePending)});state.site.hero.image=replacePending(state.site.hero.image);state.site.announcements.forEach(item=>item.image=replacePending(item.image));state.site.testimonials.forEach(item=>item.image=replacePending(item.image))}
async function syncProductPages(){
  const previousProducts=new Map((state.publishedCatalog?.products||[]).map(product=>[product.id,product]));
  const currentProducts=new Map(state.catalog.products.map(product=>[product.id,product]));
  const previousCategories=new Map((state.publishedCatalog?.categories||[]).map(category=>[category.slug,category]));
  for(const product of state.catalog.products){
    const category=state.catalog.categories.find(item=>item.slug===product.category),previous=previousProducts.get(product.id),previousCategory=previousCategories.get(product.category);
    if(previous&&JSON.stringify(previous)===JSON.stringify(product)&&JSON.stringify(previousCategory)===JSON.stringify(category))continue;
    const path=ProductPageGenerator.productPath(product),html=ProductPageGenerator.generateProductHtml(product,category);
    await saveTextFile(path,html,`Actualizează pagina produsului ${product.name}`);
  }
  for(const product of previousProducts.values()){
    if(!currentProducts.has(product.id))await deleteTextFile(ProductPageGenerator.productPath(product),`Șterge pagina produsului ${product.name}`);
  }
}
async function publish(){const button=$('[data-publish]');button.disabled=true;button.textContent='Se publică…';try{await uploadPending();applyUploadedPaths();if(state.dirty.has('catalog')){await syncProductPages();const result=await saveFile('data/catalog.json',state.catalog,state.shas.catalog,'Actualizează mobilierul din panoul simplu');state.shas.catalog=result.content?.sha||result.sha||state.shas.catalog;state.publishedCatalog=cloneData(state.catalog)}if(state.dirty.has('site')){const result=await saveFile('data/site.json',state.site,state.shas.site,'Actualizează pagina, noutățile și clienții');state.shas.site=result.content?.sha||result.sha||state.shas.site}state.dirty.clear();state.changes=0;state.uploads.clear();$('[data-publish-bar]').hidden=true;renderProducts();renderNews();renderTestimonials();fillSettings();toast('Publicat! Site-ul se actualizează automat în câteva momente.')}catch(error){console.error(error);toast(`Nu am putut publica: ${error.message}`,true)}finally{button.disabled=false;button.textContent='Publică modificările pe site'}}

function bindEvents(){
  $$('[data-tab]').forEach(button=>button.addEventListener('click',()=>{$$('[data-tab]').forEach(item=>item.classList.toggle('active',item===button));$$('[data-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.panel===button.dataset.tab))}));
  $('[data-product-search]').addEventListener('input',renderProducts);$('[data-category-filter]').addEventListener('change',renderProducts);$('[data-add-product]').addEventListener('click',()=>openProduct());$('[data-product-form]').addEventListener('submit',saveProduct);$$('[data-close-product]').forEach(button=>button.addEventListener('click',()=>$('[data-product-dialog]').close()));
  $('[data-edit-gallery]').addEventListener('click',event=>{const remove=event.target.closest('[data-remove-gallery]');if(!remove)return;const host=$('[data-edit-gallery]'),gallery=JSON.parse(host.dataset.gallery||'[]');gallery.splice(Number(remove.dataset.removeGallery),1);host.dataset.gallery=JSON.stringify(gallery);renderEditGallery()});
  $('[data-product-list]').addEventListener('click',event=>{const edit=event.target.closest('[data-edit-product]'),remove=event.target.closest('[data-delete-product]');if(edit)openProduct(Number(edit.dataset.editProduct));if(remove)deleteProduct(Number(remove.dataset.deleteProduct))});
  $('[data-add-news]').addEventListener('click',()=>openNews());$('[data-news-form]').addEventListener('submit',saveNews);$$('[data-close-news]').forEach(button=>button.addEventListener('click',()=>$('[data-news-dialog]').close()));
  $('[data-news-list]').addEventListener('click',event=>{const edit=event.target.closest('[data-edit-news]'),remove=event.target.closest('[data-delete-news]');if(edit)openNews(Number(edit.dataset.editNews));if(remove)deleteNews(Number(remove.dataset.deleteNews))});
  $('[data-add-testimonial]').addEventListener('click',()=>openTestimonial());$('[data-testimonial-form]').addEventListener('submit',saveTestimonial);$$('[data-close-testimonial]').forEach(button=>button.addEventListener('click',()=>$('[data-testimonial-dialog]').close()));
  $('[data-testimonial-list]').addEventListener('click',event=>{const edit=event.target.closest('[data-edit-testimonial]'),remove=event.target.closest('[data-delete-testimonial]');if(edit)openTestimonial(Number(edit.dataset.editTestimonial));if(remove)deleteTestimonial(Number(remove.dataset.deleteTestimonial))});
  $('[data-settings-form]').addEventListener('submit',saveSettings);$('[data-publish]').addEventListener('click',publish);$('[data-logout]').addEventListener('click',()=>netlifyIdentity.logout())
}

async function start(user){if(state.started)return;state.started=true;state.user=user;$('[data-login-screen]').hidden=true;$('[data-app]').hidden=false;$('[data-user-email]').textContent=user.email||'';try{const [catalog,site]=await Promise.all([loadFile('data/catalog.json'),loadFile('data/site.json')]);state.catalog=catalog.data;state.publishedCatalog=cloneData(catalog.data);state.site=site.data;state.site.announcements||=[];state.site.testimonials||=[];state.shas={catalog:catalog.sha,site:site.sha};populateCategories();renderProducts();renderNews();renderTestimonials();fillSettings();bindEvents()}catch(error){console.error(error);toast(`Nu am putut încărca datele: ${error.message}`,true)}}
function showLogin(){state.started=false;state.user=null;$('[data-app]').hidden=true;$('[data-login-screen]').hidden=false}

$('[data-login]').addEventListener('click',()=>netlifyIdentity.open('login'));
netlifyIdentity.on('init',user=>user?start(user):showLogin());
netlifyIdentity.on('login',user=>{netlifyIdentity.close();start(user)});
netlifyIdentity.on('logout',showLogin);
